#!/bin/sh
./scr/run_sim.sh rv32ui-p-add
./scr/run_sim.sh rv32ui-p-addi
./scr/run_sim.sh rv32ui-p-and
./scr/run_sim.sh rv32ui-p-andi
./scr/run_sim.sh rv32ui-p-auipc
./scr/run_sim.sh rv32ui-p-beq
./scr/run_sim.sh rv32ui-p-bge
./scr/run_sim.sh rv32ui-p-bgeu
./scr/run_sim.sh rv32ui-p-blt
./scr/run_sim.sh rv32ui-p-bltu
./scr/run_sim.sh rv32ui-p-bne
./scr/run_sim.sh rv32ui-p-fence_i
./scr/run_sim.sh rv32ui-p-jal
./scr/run_sim.sh rv32ui-p-jalr
./scr/run_sim.sh rv32ui-p-lb
./scr/run_sim.sh rv32ui-p-lbu
./scr/run_sim.sh rv32ui-p-lh
./scr/run_sim.sh rv32ui-p-lhu
./scr/run_sim.sh rv32ui-p-lui
./scr/run_sim.sh rv32ui-p-lw
./scr/run_sim.sh rv32ui-p-or
./scr/run_sim.sh rv32ui-p-ori
./scr/run_sim.sh rv32ui-p-sb
./scr/run_sim.sh rv32ui-p-sh
./scr/run_sim.sh rv32ui-p-simple
./scr/run_sim.sh rv32ui-p-sll
./scr/run_sim.sh rv32ui-p-slli
./scr/run_sim.sh rv32ui-p-slt
./scr/run_sim.sh rv32ui-p-slti
./scr/run_sim.sh rv32ui-p-sltiu
./scr/run_sim.sh rv32ui-p-sltu
./scr/run_sim.sh rv32ui-p-sra
./scr/run_sim.sh rv32ui-p-srai
./scr/run_sim.sh rv32ui-p-srl
./scr/run_sim.sh rv32ui-p-srli
./scr/run_sim.sh rv32ui-p-sub
./scr/run_sim.sh rv32ui-p-sw
./scr/run_sim.sh rv32ui-p-xor
./scr/run_sim.sh rv32ui-p-xori
